---
title: ""
author: "Rodrigo Arcoverde Cerveira"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
output: html_document
abstract: Short project description.
knit: (function(inputFile, encoding) {
          rmarkdown::render(inputFile,
                            encoding = encoding, 
                            output_file = paste0(
                              xfun::sans_ext(inputFile), '_', Sys.Date(), '.html'),
                                output_dir = "../results/lab_book/")})
---

```{r setup, include=FALSE}
knitr::opts_knit$set(echo = TRUE,
                     root.dir = getwd(),
                     fig.width = 6, fig.height = 5,
                     warning = FALSE, 
                     message = FALSE)

result.dir <- paste0("results/",Sys.Date(),"/")

## creates result.dir with date in if not existent
ifelse(isFALSE(dir.exists(paste0("../",result.dir))), dir.create(paste0("../",result.dir),recursive = TRUE),"Result directory for today exists already!")
options(stringsAsFactors = FALSE) 
```

## Needed libraries
```{r libraries, message=FALSE}
library(data.table)
library(ggplot2)
library(dplyr)
library(tidyr)
library(cowplot)
library(stringr)
library(ggtree)
library(treeio)
library(seqRFLP)
library(Biostrings)
library(msa)
library(treeio)
library(ggtree)
library(RColorBrewer)
library(ggnewscale)

```

## Load data
```{r message=FALSE, warning=FALSE, echo=FALSE}
#binding summary tables
ls <- list.files("~/Box Sync/public_repertoire/results/2020-09-13/public-tables", full.names = T)
ls <- grep("summary", ls, value = T)
df <- lapply(ls, read.csv)
names(df) <- c("B1", "B2", "PV")
df <- rbindlist(df, idcol = T)


#combining animals
rem_dup.one <- function(x){
  paste(unique(toupper(trimws(unlist(strsplit(x,split="(?!')[ [:punct:]]",fixed=F,perl=T))))),collapse = ", ")
}
rem_dup.vector <- Vectorize(rem_dup.one,USE.NAMES = F)

df_f <-  df %>% 
  mutate(combined_animals = paste0(animals_rep_seq, sep = ", ", animals_sc)) 

df_f$combined_animals <- rem_dup.vector(df_f$combined_animals)
df_f$combined_animals <- gsub(", , ", ", ",df_f$combined_animals)
df_f$.id <- gsub("IgM", "PV", df_f$.id)
df_f$sequence <- sub("+", "",df_f$sequence)
df_comb <- df_f %>% mutate(number_animals_combined = str_count(combined_animals, "E"))
groups <- data.frame(NP = c("E11", "E16", "E17", "E23", "E24"),
                     SOL = c("E12", "E14", "E18", "E21", NA))
ff = function(x, patterns, replacements = patterns, fill = NA, ...)
{
  stopifnot(length(patterns) == length(replacements))
  
  ans = rep_len(as.character(fill), length(x))    
  empty = seq_along(x)
  
  for(i in seq_along(patterns)) {
    greps = grepl(patterns[[i]], x[empty], ...)
    ans[empty[greps]] = replacements[[i]]  
    empty = empty[!greps]
  }
  
  return(ans)
}
df_comb$NP <- ff(df_comb$combined_animals, 
                     patterns = c("E11", "E16", "E17", "E23", "E24"), 
                     replacements = c("NP","NP","NP","NP","NP"))
df_comb$SOL <- ff(df_comb$combined_animals, 
                  patterns = c("E12", "E14", "E18", "E21"), 
                  replacements = c("SOL","SOL","SOL","SOL"))

df_comb <- df_comb %>%
  mutate(Groups = ifelse(!is.na(df_comb$NP) & !is.na(df_comb$SOL),
                         "Both",
                         ifelse(!is.na(df_comb$NP) & is.na(df_comb$SOL),
                                "NP",
                                ifelse(is.na(df_comb$NP) & !is.na(df_comb$SOL),
                                       "SOL", ""))),
         E11_and_E16 = ifelse(grepl("^E11, E16$",combined_animals),"YES", "NO"))
filtered <- df_comb %>% filter(number_animals_combined >= 2)


```



```{r data_prep}
#function to create clonoquery file first
.clono_full <- function(z){
ls <- list.files(z, full.names = T)
ls <- grep("full.txt", ls, value = T)
print(ls)
  if(length(ls) != 9) {
    stop("Folder not containing 9 files, please check the number of files or change the function to allow a different number of files.")
  }
  if(any(!grepl("full",ls))){
    stop("Files in the folder are not identified as a full file in its name.")
  }
  else{
    x <- lapply(ls, fread, fill = T)
    names(x) <- c("E11", "E12", "E14", "E16", "E17", "E18", "E21", "E23", "E24")
    x <- lapply(x, function (x) x[!apply(is.na(x) | x == "", 1, all),])       
    x_all <- do.call(rbind, x)
#getting the clonoquery named properly, all clones queries, aka full table
    x_m_full <- x_all %>% 
      mutate(grp = cumsum(grepl("Query",name))) %>%
      group_by(grp) %>% 
      mutate(clonoquery = ifelse(row_number() > 1, dplyr::first(name), name)) %>%
      ungroup() %>% 
      select(-c(grp)) %>%
      relocate(clonoquery) %>%
      mutate(clone = substr(clonoquery, 10,14))
    }
return(x_m_full)
}

###### COMBINING CLONOQUERY FULL v4_NGS TR1 #######
clonoquery_full_B2 <- .clono_full(
  "~/Box Sync/RSV NGS/v4_Analysis/v4_public-repertoire/analysis/v4/results/2020-09-13/clonoquery/B2")

###### COMBINING CLONOQUERY FULL v4_B1-D14 #######
clonoquery_full_B1 <- .clono_full(
  "~/Box Sync/RSV NGS/v4_Analysis/v4_public-repertoire/analysis/v4/results/2020-09-13/clonoquery/B1")

###### COMBINING CLONOQUERY FULL igM #######
clonoquery_full_igm <- .clono_full(
  "~/Box Sync/RSV NGS/v4_Analysis/v4_public-repertoire/analysis/v4/results/2020-09-13/clonoquery/IgM/")

##### Combining all the clonoquery full files into a single file #######
## output as CSV file with a new column for time_point

combined_full <- list(clonoquery_full_igm, clonoquery_full_B1, clonoquery_full_B2)
names(combined_full) <- c("PV", "B1", "B2") 
combined_full  <- rbindlist(combined_full, idcol = T, fill = T)  
combined_full  <- combined_full %>% dplyr::rename(time_point = .id) %>% filter(count > 0)

filtered_np <- merge(filtered, combined_full, by = "clone")
filtered_np <- filtered_np %>%
  mutate(E11_and_E16 = ifelse(grepl("^E11, E16$",combined_animals),"YES", "NO"))


```

```{r plot_4, eval=FALSE}
set.seed(50)
filtered_to_fasta <- filtered_np %>% group_by(clone) %>% sample_n(size = 1) %>% select(clone,VDJ_nt, VDJ_aa, .id)

filtered_to_fasta_nt <- filtered_to_fasta %>% select(clone,VDJ_nt) %>% as.data.frame()

filtered_to_fasta_aa <- filtered_to_fasta %>% select(clone,VDJ_aa) %>% as.data.frame()


dataframe2fas(filtered_to_fasta_nt, "~/Box Sync/public_repertoire/results/2020-10-05/public-clones_nt.fasta")
dataframe2fas(filtered_to_fasta_aa, "~/Box Sync/public_repertoire/results/2020-10-05/public-clones_aa.fasta")


p_nt <- readBStringSet("~/Box Sync/public_repertoire/results/2020-10-05/public-clones_nt.fasta")
p_aa <- readBStringSet("~/Box Sync/public_repertoire/results/2020-10-05/public-clones_aa.fasta")

p_nt_msa <- msaMuscle(p_nt, verbose = T, type = "dna")
p_aa_msa <- msaMuscle(p_aa, verbose = T, type = "protein")

writeXStringSet(BStringSet(p_nt_msa), 
                "~/Box Sync/public_repertoire/results/2020-10-05/public-clones_nt_msa.fasta")
writeXStringSet(BStringSet(p_aa_msa), 
                "~/Box Sync/public_repertoire/results/2020-10-05/public-clones_aa_msa.fasta")
```

## Tree 


```{r ploting_tree}
t1 <- treeio::read.tree( 
  "~/Box Sync/public_repertoire/results/2020-10-05/aa_fastree_result.tre")

t2 <- ggtree(t1) + geom_tiplab(align = T, size = 2)

df_tree <- df_comb %>% group_by(clone) %>% 
  mutate(PV = ifelse(.id == "PV", size_rep_seq, 0),
         B1 = ifelse(.id == "B1", size_rep_seq, 0),
         B2 = ifelse(.id == "B2", size_rep_seq, 0)) %>%
  summarise_each(funs(if(is.numeric(.)) max(., na.rm = TRUE) else dplyr::first(.))) %>%
  dplyr::rename(label = clone) %>%
  select(label, PV,B1, B2, Groups, number_animals_combined, E11_and_E16) %>% 
  filter(label != "P0508") %>% as.data.frame()
rownames(df_tree) <- df_tree$label

t2_h <- gheatmap(t2, df_tree[, "Groups", drop = FALSE], width = 0.5, color = "black", offset = 0.1) +
  scale_fill_manual(breaks = c("Both", "NP", "SOL"), values = c("#107F01","#065386", "#5C003C"), "Groups")
t3_h <- t2_h + new_scale_fill()
t4_h <- gheatmap(t3_h, df_tree[, c("PV", "B1", "B2"), drop = FALSE], width = 0.5, offset = 0.1) +
  scale_fill_gradient("Clone size (log10)", low = "white", high = "red", trans="pseudo_log")
t5_h <- t4_h + new_scale_fill()
t6_h <- gheatmap(t5_h, df_tree[, "number_animals_combined", drop = FALSE], width = 0.5, offset = 0.9) +
  scale_fill_gradient("Number of animals", low = "white", high = "blue")

t6_h
t4_h

combined_full <- combined_full %>% mutate(label = clone)
v_gene <- merge(df_tree, combined_full, by = "label") %>% group_by(clone) %>%
  summarise_each(funs(if(is.numeric(.)) max(., na.rm = TRUE) else dplyr::first(.))) %>% mutate(V_gene = gsub("-.*","", V_gene)) %>% relocate(label) %>% as.data.frame()
rownames(v_gene) <- v_gene$label

t_v <- ggtree(t1, layout = "circular") + geom_tiplab(size = 1.5, align = T)
v_h <- gheatmap(t_v, v_gene[, "V_gene", drop = FALSE], width = 0.5, color = "black", offset = 1.1) +
  scale_fill_manual(breaks = c("IGHV1", "IGHV2","IGHV3", "IGHV4", "IGHV5", "IGHV7"), values = brewer.pal(6, "Dark2"))
v_h <- v_h + new_scale_fill()
v_h2 <- gheatmap(v_h, v_gene[, "Groups", drop = FALSE], width = 0.5, color = "black", offset = 0.01) +
  scale_fill_manual(breaks = c("Both", "NP", "SOL"), values = c("#107F01","#065386", "#5C003C"), "Groups")
v_h2

#t2_h <- gheatmap(t2, df_tree[, "E11_and_E16", drop = FALSE], width = 1, color = "black", offset = 0.1) +
#  scale_fill_manual(breaks = c("YES", "NO"), values = c("red", "blue"), "Present E11 and E16 only")
#t2_h

```

```{r testing, eval=FALSE}
#####   TESTTING PLOTTING #######
anole.tree<-read.tree("http://www.phytools.org/eqg2015/data/anole.tre")
svl <- read.csv("http://www.phytools.org/eqg2015/data/svl.csv",
    row.names=1)
svl <- as.matrix(svl)[,1]
fit <- phytools::fastAnc(anole.tree,svl,vars=TRUE,CI=TRUE)

td <- data.frame(node = nodeid(anole.tree, names(svl)),
               trait = svl)
nd <- data.frame(node = names(fit$ace), trait = fit$ace)

d <- rbind(td, nd)
d$node <- as.numeric(d$node)
tree <- full_join(anole.tree, d, by = 'node')
ggtree(tree, layout = "rectangular", aes(color=trait), continuous = TRUE, yscale = "trait") + 
    scale_color_viridis_c() + theme_minimal()

library(ggimage)
library(ggtree)
url <- paste0("https://raw.githubusercontent.com/TreeViz/",             "metastyle/master/design/viz_targets_exercise/")

x <- read.tree(paste0(url, "tree_boots.nwk"))
info <- read.csv(paste0(url, "tip_data.csv"))

p <- ggtree(x) %<+% info + xlim(-.1, 4)
p2 <- p + geom_tiplab(offset = .6, hjust = .5) +
    geom_tippoint(aes(shape = trophic_habit, color = trophic_habit, size = mass_in_kg)) + 
    theme(legend.position = "right") + scale_size_continuous(range = c(3, 10))
p2
```

## SessionInfo
```{r}
sessionInfo()
```

